shortner/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'shortner'

urlpatterns = [
    path('login/', views.userlogin, name="login"),
    path('', views.index, name="index"),
    path('log_out/', views.userlogout, name="userlogout"),
    path('sign_up/', views.usersignup, name="signup"),
    path('<short_url>/', views.redirect, name="redirect"),

]

urlshortner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shortner.urls')),
]

shortner/models.py
from django.db import models
from django.contrib.auth.models import User


class URL(models.Model):
    full_url = models.URLField(max_length=200)
    short_url = models.SlugField(max_length=6)
    clicks = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.full_url)[:40]

shortner/forms.py
from django import forms
from django.core.validators import URLValidator, EmailValidator
from django.forms import CharField




class SubmitURLForm(forms.Form):
    URL_Field = forms.URLField(label='', widget=forms.TextInput(
        attrs={'placeholder': 'Ex: https://facebook.com'}))

class SignupForm(forms.Form):
    username = forms.CharField(label='Username',widget=forms.TextInput(attrs={'placeholder':'Enter your username'}))
    email = forms.EmailField()
    password = forms.CharField(label ='Password', widget=forms.PasswordInput(attrs={'placeholder':'Enter a Password'}))
    confirmPassword = forms.CharField(label = 'Confirm Password',widget=forms.PasswordInput(attrs={'placeholder':'Enter your password again'}))

shortner/views.py
from django.shortcuts import render, redirect
from .models import URL
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SubmitURLForm, SignupForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from .code_generator import generate


@login_required(login_url='/login/')
def index(request):
    if request.method == "GET":
        form = SubmitURLForm()
        context = {
            'form': form,
            'title': 'URL Shortner'
        }
    else:
        form = SubmitURLForm(request.POST)
        if form.is_valid():
            try:
                url = URL.objects.get(full_url=form.cleaned_data['URL_Field'])
            except:
                pass
            else:
                code = url.short_url
                context = {
                    'form': form,
                    'title': 'URL Shortner',
                    'shortened_url': 'https://tiny-url-service.herokuapp.com/' + code,
                }
                return render(request, 'shortner/index.html', context)
            while True:
                code = generate(6)
                try:
                    urlobj = URL.objects.get(short_url=code)
                except:
                    break
            url = URL(
                full_url=form.cleaned_data['URL_Field'], short_url=code, user=request.user)
            url.save()
        context = {
            'form': form,
            'title': 'URL Shortner',
            'shortened_url': 'https://tiny-url-service.herokuapp.com/' + code,
        }
    return render(request, 'shortner/index.html', context)


def redirect(request, short_url):
    try:
        url = URL.objects.get(short_url=short_url)
    except:
        return HttpResponse("Page you were looking for was not found on our sever")
    url.clicks += 1
    url.save()
    return (HttpResponseRedirect(url.full_url))


def userlogin(request):
    if request.method == 'GET':
        context = {
            'could_not_log_in': False,
        }
        return render(request, 'shortner/login.html', context)
    else:
        username = request.POST.get('Username')
        password = request.POST.get('Password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            context = {
                'could_not_log_in': True,
            }
        return render(request, 'shortner/login.html', context)


def userlogout(request):
    logout(request)
    context = {
        'could_not_log_in': False
    }
    logout(request)
    return HttpResponseRedirect('/login')


def usersignup(request):
    if request.method == 'GET':
        form = SignupForm()
        return render(request, 'shortner/signup.html', {'form': form})
    else:
        form = SignupForm(request.POST)
        if form.is_valid():
            # if username is taken
            try:
                user = User.objects.get(username=form.cleaned_data['username'])
            except:
                pass
            else:
                error_message = 'Username %s is already taken.' % (
                    form.cleaned_data['username'])
                return render(request, 'shortner/signup.html', {'form': form, 'error_message': error_message})

            try:
                user = User.objects.get(email=form.cleaned_data['email'])
            except:
                pass
            else:
                error_message = 'Email %s is already being used.' % (
                    form.cleaned_data['email'])
                return render(request, 'shortner/signup.html', {'form': form, 'error_message': error_message})
            # if passwords match
            if form.cleaned_data['password'] == form.cleaned_data['confirmPassword']:
                user = User.objects.create_user(
                    form.cleaned_data['username'], form.cleaned_data['email'], form.cleaned_data['password'])
                user.save()
                return render(request, 'shortner/signup.html', {'form': form, 'error_message': 'Account created successfully'})
            else:
                error_message = 'Passwords don\'t match.'
                return render(request, 'shortner/signup.html', {'form': form, 'error_message': error_message})

shortner/templates/shortner/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            Short it - URL Shortner
        </title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">
        
    </head>
    <body style="background:url({% static 'background.jpg' %})">
        <div>
            <a href="{% url 'shortner:userlogout'%}" style="margin-left:94%;font-family:Arial, Helvetica, sans-serif;">
                Logout
            </a>
        </div>
        <div class="heading">{{title}}</div>
        <div class="content">
            <form action="." method="POST">
                {% csrf_token %}
                    <div class= "textbox" >
                    {{form.as_p}}
                    </div>
                    <input type="submit" value="Shorten It!" class="submitButton">
            </form>
            {% if shortened_url %}
            <a href="{{ shortened_url }}" target="_blank">{{ shortened_url }}</a>
            {% endif %}
        </div>
    </body>
</html>

shortner/templates/shortner/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="{% static 'login.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Fredoka+One" rel="stylesheet">

        <title> Shorten It! URL Shortner</title>
    </head>
    <body style="background:url({% static 'background.jpg' %})">
        <div class="heading">URL Shortner</div>
        <br>
        <div class="content">
            <form action='.', method="POST">
                {% csrf_token %}
                <input type="text" placeholder="Username" name="Username" class="textbox"></input>
                <br>
                <input type="password" placeholder="Password" name="Password" class="textbox"></input>
                <br>
                <input type="submit" value="Login" class="submitButton">
                <br><br>
                 <a href="{%url 'shortner:signup' %}">Don't have an account? Sign Up</a>
            </form>
            {%if could_not_log_in %}
            <p class="error">Either username or password is incorrect</p>
            <a href="/forgot_password">Forgot Password?</a>
            {% endif %}
        </div>
    </body>
</html>

shortner/templates/shortner/signup.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Shorten It! URL Shortner</title>
    <link rel="stylesheet" href="{% static 'signup.css' %}" />
    <link
      href="https://fonts.googleapis.com/css?family=Fredoka+One"
      rel="stylesheet"
    />
  </head>
  <body style="background:url({% static 'background.jpg' %})">
    <div class="heading">Sign Up</div>
    <div class="content">
      <div class="error">
        {%if error_message %}
        {{ error_message }}
        {% endif %}
      </div>
        <form action="." method="POST">
          {% csrf_token %}
          <div class="textbox">
            {{ form.as_p }}
          </div>
          <input
            type="submit" value="Sign up" name="Sign up" class="submitButton"/>
        </form>
        <br>
        <span  class="error">Already Have an account?</span>
        <a href="{%url 'shortner:login' %}" class="error"
         id="signin" style="margin-left:34%;font-size:25px;
         font-family:Arial, Helvetica, sans-serif;">
         Sign in
        </a>
      </div>
  </body>
</html>